#!/bin/sh
mkdir -p /var/drive/client/
mkdir -p /etc/drive

chmod 0755 /var/drive/client

systemctl daemon-reload

systemctl enable bdfsclient.service

bdfsconf="/etc/drive/bdfs.conf"

echo "Current Drive Daemon configurations is following, change it if neccessary in $bdfsconf"
cat $bdfsconf

service bdfsclient restart
